# playbook set of plays ,, play is some of tasks(actions)
- name: task 1 # play name
  # hosts: 35.175.250.33 #hard coded
  hosts: web # alias
  become: true # to use sudo , use root user
  # vars:

  tasks:
#---------------------------------------------------------#
    - name: include vars
      include_vars:
        file: variables.yaml
    
    - name: update packages #task name
      apt:  #module name 
        update_cache : true

    - name: install nginx #task name
      apt: #module name 
        name: nginx
        state: present #maybe be absense

    # - name: create dir and index.html #task name
    #   command: mkdir /home/ubuntu/htmls

    - name: create dir and index.html #task name
      file:
        path: /home/ubuntu/htmls
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        # owner: root
        # group: root        
        mode: '777'

# ----------------------------------------------------------#

# - name: nodejs config # play name
#   # hosts: 35.175.250.33 #hard coded
#   hosts: web fawzy # alias
#   # become: true # to use sudo
#   tasks:

    # - name: install node.js
    #   apt: 
    #     name: nodejs
    #     state: present #maybe be absense
    #   when: ansible_os_family == 'centos'



    # - name: install npm
    #   apt: 
    #     name: npm
    #     state: present #to remove it
#----------------------------------------------------# Error
    - name: execute script
      shell: ./print_echo.sh #path of script on my machine
      args:
        chdir: /home/ubuntu/htmls
#------------------------------------------------------#
    # - name: create file
    #   command : echo "{{ nginx_content }}" > /home/ubuntu/htmls/index.html
    # - name: create file
    #   file: 
    #     path: /home/ubuntu/htmls/index.html
    #     state: touch #file to edit permission or do something on the file
    #     owner: "{{ user }}"
    #     group: "{{ user }}"        
    #     mode: '777'
    - name: Remove old html
      file:
        path: /home/ubuntu/htmls/index.html
        state: absent
      become: true

    - name: add line in file
      lineinfile: 
        path: /home/ubuntu/htmls/index.html
        line: "{{ nginx_content }} " # jenja template
        create: yes
        owner: "{{ user }}"
        group: "{{ user }}"        
        mode: '644'

    - name: copy file
      copy:
        remote_src: true
        src: /home/ubuntu/htmls/index.html
        dest: /var/www/html/index.html

    - name: config listening port
      lineinfile: 
        path: /etc/nginx/sites-available/default
        regexp: "listen 80 default_server;"
        line: "listen 8090 default_server ;"

    - name: restart nginx 
      service:  
         name: nginx  
         state: restarted  
         enabled: yes
    


# install apache on 2 machine and change port from 80 to 8090 , custom page 
# 