# - name: installing proxy  # play name
#   hosts: jumphost  # alias
#   become: true # to use sudo , use root user
#   tasks:
#---------------------------------------------------------#
- name: update packages #task name
  apt:  #module name 
    update_cache : true
#---------------------------------------------------------#

- name: install nginx #task name
  apt: #module name 
    name: nginx
    state: present #maybe be absent
#--------------------------------------------------------#
- name: config proxy
  lineinfile: 
    path: /etc/nginx/sites-available/default
    regexp: "^	location / {"
    firstmatch : true
    line: "location / {
            proxy_pass http://private-lb-260471039.us-east-1.elb.amazonaws.com ;"
#---------------------------------------------------------#
- name: restart nginx 
  service:  
     name: nginx  
     state: restarted  
     enabled: yes